[tool.poetry]
name = "coctails-api"
version = "0.1.0"
description = ""
authors = ["Dmitry Erlikh <derlih@gmail.com>"]
readme = "README.md"
packages = [{ include = "coctails_api" }]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
