name: CI
on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_TOKEN }}

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Install poetry plugins
        run: poetry self add poetry-plugin-export

      - uses: actions/cache@v3
        name: Cache deps
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install the project dependencies
        run: poetry install

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run linters
        run: poetry run poe lint

      - name: Run the automated tests
        run: poetry run poe test-ci

      - name: Export dependencies to requirements.txt
        run: poetry export --without-hashes --output requirements.txt

      - name: Commit requirements.txt
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update requirements.txt
          file_pattern: requirements.txt

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
